---
name: booklyapp
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  go_router: ^11.1.4
  dartz: ^0.10.1
  dio: ^5.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  cached_network_image: ^3.3.0
dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
flutter:
  uses-material-design: true
  assets:
  - assets/
  fonts:
  - family: GT Sectra Fine
    fonts:
    - asset: assets/fonts/GT Sectra Fine Regular.ttf
